### ISSUE TITLE
Smallest Bubble Unsized and Sizing Fails If All Bubbles Equal

### ISSUE THREAD

**Issue by OptrixAU** [lflores/gravity-bubbles#15]
The smallest item in the chart doesn't appear to scale at all - in the fiddle attached, the 'Positive' bubble should be much larger than it is.

This always occurs with the smallest item, regardless of the number of items. 

http://jsfiddle.net/5vqLswwx/1/

**Comment by OptrixAU** [comment]
In a possibly-related bug, if each of the bubbles have the exact same value (ie. 3x bubbles at 240 each), they all become 5-pixel circles. The scaling fails entirely.

**Comment by OptrixAU** [comment]
The issue with items of the exact same value can be resolved by adding this check immediately under this._calculate_groups()....

`if (this.min_amount == this.max_amount)
    {
        this.min_amount -= 1;
        this.max_amount += 1;
    }`

**Comment by lflores** [comment]
Great @OptrixAU thank you for your fix. I will test it and I will release it.
Regards

**Comment by lflores** [comment]
Thank you @OptrixAU, your code has been added to master.
Regards
