### ISSUE TITLE
Sizes are Ratio-Based, not Value-Based

### ISSUE THREAD

**Issue by OptrixAU** [lflores/gravity-bubbles#17]
The sizes of your bubbles are based on the ratio between them (the smallest value is always the minimum size, even if all of the values are high and close together).

This is a very good visualization for some purposes, but it doesn't work for others.

I made a quick change and added the 'zeroBased' configuration option. When true, this sets the minimum range of the bubble scale to zero where it's not negative. 

This means that the bubbles scale appropriately to their _value_ rather than to their _ratio_ with one-another.

Changes available on my fork - https://github.com/OptrixAU/gravity-bubbles

[Note: I haven't made a pull request because I don't have a minify tool installed at the moment - once I've got some time, I'll try and push this update to you]

**Comment by lflores** [comment]
It's good idea @OptrixAU , thanks your your help and code, I'm working on integrate your pull request.

**Comment by lflores** [comment]
Thank you @OptrixAU, your code has been added to master.
