### ISSUE TITLE
The texts should not be selectable

### ISSUE THREAD

**Issue by lflores** [lflores/gravity-bubbles#4]
Texts of bubble labels and group labels should not be selectables, does an ugly effect.

**Comment by headwinds** [comment]
you might want to make that configuration but its also pretty easy to solve with styling. 

I agree with you though. If I need to copy the text from a bubble, I would find a different way to do so without selecting it.

**Comment by lflores** [comment]
It has been solved in version 1.0.1.
@headwinds please, could you check?
